<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"教师管理",
			            "menuJump":"列表",
			            "tableName":"jiaoshi"
			        }
			    ],
			    "menu":"教师管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"用户管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"用户管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"实验室信息管理",
			            "menuJump":"列表",
			            "tableName":"shiyanshi"
			        }
			    ],
			    "menu":"实验室信息管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"有形资产管理",
			            "menuJump":"列表",
			            "tableName":"youxing"
			        }
					,
					{
					    "buttons":[
					        "查看",
					        "删除"
					    ],
					    "menu":"维修记录管理",
					    "menuJump":"列表",
					    "tableName":"weixiu"
					}
					,
					{
					    "buttons":[
					        "查看",
					        "删除"
					    ],
					    "menu":"借用记录管理",
					    "menuJump":"列表",
					    "tableName":"jieyong"
					}
			    ],
			    "menu":"有形资产管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"无形资产管理",
			            "menuJump":"列表",
			            "tableName":"wuxing"
			        }
			    ],
			    "menu":"无形资产管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"实验室活动管理",
                        "menuJump":"列表",
                        "tableName":"huodong"
                    }
					,
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"请假管理",
					    "menuJump":"列表",
					    "tableName":"qingjia"
					}
                ],
                "menu":"实验室活动管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"活动类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryHuodong"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"公告类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"物品类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryYouxing"
			        }
			    ],
			    "menu":"基础数据管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"公告管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告管理"
			}
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
		"backMenu":[
		    {
				"child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"实验室信息管理",
			            "menuJump":"列表",
			            "tableName":"shiyanshi"
			        }
			    ],
			    "menu":"实验室信息管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "记录",
			                "删除"
			            ],
			            "menu":"有形资产管理",
			            "menuJump":"列表",
			            "tableName":"youxing"
			        }
					,
					{
					    "buttons":[
					        "查看",
					        "删除"
					    ],
					    "menu":"维修记录管理",
					    "menuJump":"列表",
					    "tableName":"weixiu"
					}
					,
					{
					    "buttons":[
					        "查看",
					        "删除"
					    ],
					    "menu":"借用记录管理",
					    "menuJump":"列表",
					    "tableName":"jieyong"
					}
			    ],
			    "menu":"有形资产管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "审核",
			                "删除"
			            ],
			            "menu":"无形资产管理",
			            "menuJump":"列表",
			            "tableName":"wuxing"
			        }
			    ],
			    "menu":"无形资产管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"实验室活动管理",
	                    "menuJump":"列表",
	                    "tableName":"huodong"
	                }
					,
					{
					    "buttons":[
					        "查看",
					        "审核",
					        "删除"
					    ],
					    "menu":"请假管理",
					    "menuJump":"列表",
					    "tableName":"qingjia"
					}
	            ],
	            "menu":"实验室活动管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改"
			            ],
			            "menu":"活动类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryHuodong"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改"
			            ],
			            "menu":"物品类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryYouxing"
			        }
			    ],
			    "menu":"基础数据管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"公告管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告管理"
			}
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"教师",
	    "tableName":"jiaoshi"
	}
	,
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"实验室信息管理",
			            "menuJump":"列表",
			            "tableName":"shiyanshi"
			        }
			    ],
			    "menu":"实验室信息管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"有形资产管理",
			            "menuJump":"列表",
			            "tableName":"youxing"
			        }
					,
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"维修记录管理",
					    "menuJump":"列表",
					    "tableName":"weixiu"
					}
					,
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"借用记录管理",
					    "menuJump":"列表",
					    "tableName":"jieyong"
					}
			    ],
			    "menu":"有形资产管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"无形资产管理",
			            "menuJump":"列表",
			            "tableName":"wuxing"
			        }
			    ],
			    "menu":"无形资产管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"实验室活动管理",
	                    "menuJump":"列表",
	                    "tableName":"huodong"
	                }
					,
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
							"删除"
					    ],
					    "menu":"请假管理",
					    "menuJump":"列表",
					    "tableName":"qingjia"
					}
	            ],
	            "menu":"实验室活动管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"公告管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告管理"
			}
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
